blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://registry.terraform.io/providers/arslanbekov/statusgator/latest/docs
    about: Check the provider documentation
  - name: StatusGator API Docs
    url: https://statusgator.com/api/v3/docs?utm_source=terraform-provider&utm_medium=github&utm_campaign=statusgator-terraform
    about: StatusGator API documentation
